// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ITT0mOqy3u4g7Z8WRanEXC9FJD_x0Jo',
    appId: '1:806738862854:web:7e16bb0797e2c849fdf487',
    messagingSenderId: '806738862854',
    projectId: 'yurt-dayanisma-projesi',
    authDomain: 'yurt-dayanisma-projesi.firebaseapp.com',
    storageBucket: 'yurt-dayanisma-projesi.firebasestorage.app',
    measurementId: 'G-DTJNQ41FDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyWVpbxccyrEGrxl1OYv-7Ewxm019477M',
    appId: '1:806738862854:android:db471b166990af94fdf487',
    messagingSenderId: '806738862854',
    projectId: 'yurt-dayanisma-projesi',
    storageBucket: 'yurt-dayanisma-projesi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVGVtaTcHXujwb_yF_mpjy59G8lYjHFW4',
    appId: '1:806738862854:ios:3707f1de1b25e698fdf487',
    messagingSenderId: '806738862854',
    projectId: 'yurt-dayanisma-projesi',
    storageBucket: 'yurt-dayanisma-projesi.firebasestorage.app',
    iosBundleId: 'com.example.yurtDayanismaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVGVtaTcHXujwb_yF_mpjy59G8lYjHFW4',
    appId: '1:806738862854:ios:3707f1de1b25e698fdf487',
    messagingSenderId: '806738862854',
    projectId: 'yurt-dayanisma-projesi',
    storageBucket: 'yurt-dayanisma-projesi.firebasestorage.app',
    iosBundleId: 'com.example.yurtDayanismaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1ITT0mOqy3u4g7Z8WRanEXC9FJD_x0Jo',
    appId: '1:806738862854:web:ea3e357eaed91f2bfdf487',
    messagingSenderId: '806738862854',
    projectId: 'yurt-dayanisma-projesi',
    authDomain: 'yurt-dayanisma-projesi.firebaseapp.com',
    storageBucket: 'yurt-dayanisma-projesi.firebasestorage.app',
    measurementId: 'G-RLN3Z3MF8W',
  );
}
